#!/bin/bash

confirmyes(){
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [Y/n]} " response
    case $response in
        [yY][eE][sS]|[yY]) 
            true
            ;;
        [nN][oO]|[nN])
            false
            ;;
        *)
            true
            ;;
    esac
}

if echo "$(whoami)" | grep "root" > /dev/null 2>&1; then
  echo -en "
\E[1;33;44m
You can not run as root.

Aborting...
\E[0m

"
  exit 0
fi

read -r -p "
${1:-Enter search path:} " path

read -r -p "
${1:-Search recursive? [Y/n]} " recursive
case $recursive in
    [yY][eE][sS]|[yY]) 
        search=""
        ;;
    [nN][oO]|[nN])
        search="-maxdepth 1"
        ;;
    *)
        search=""
        ;;
esac

read -r -p "
${1:-Enter filename or expression:} " bestand
if [ "$bestand" = "" ]; then
  files="*"
else
  files="$bestand"
fi

read -r -p "
${1:-Enter text to search for:} " tekst

getlist0() {
    for file in "$(find $path $search -type f -iname "$files")" ; do
            printf "%s"'\n' "$file"
    done
}

getlist1() {
    for file in "$(find $path $search -type f -iname "$files" -exec grep -l "$tekst" {} \+)" ; do
            printf "%s"'\n' "$file"
    done
}


if [ "$tekst" = "" ]; then
  getlist0 > ~/searchstring.txt
else
  getlist1 > ~/searchstring.txt
fi

lines=$( wc -l ~/searchstring.txt  | awk '{print $1}' )
if [ "$lines" -eq "0" ]; then
  echo -en "
\E[1;33;44m
No match found
\E[0m

"
  exit 0
elif [ "$lines" -eq "1" ]; then
  size=$( wc -c `cat ~/searchstring.txt` | awk '{print $1}' )
else
  size=$( while read filename ;  do stat -c '%s' $filename ; done < ~/searchstring.txt | awk '{total+=$1} END {print total}' )
  if ! [ "$size" -eq "$size" ] 2>/dev/null; then
    echo -en "
\E[1;33;44m
####################################

Error(s) encountered while computing

the total size of matching files.

Aborting...

####################################
\E[0m
"
    exit 1
  fi
fi

last="${size:(-3)}"
second="$(($size / 1000))"
third="$(($size / 1000000))"
if [ "$size" -lt "1000" ]; then
totalsize="$( echo "$size byte" )"
elif [ "$size" -lt "1000000" ]; then
last="$( expr substr $last 1 2 )"
totalsize=$( echo "$second,$last Kb" )
elif [ "$size" -gt "999999" ]; then
second="${second:(-3)}"
second="$( expr substr $second 1 2 )"
totalsize="$( echo "$third,$second Mb" )"
fi

echo -en "
\E[1;33;44m
text or expression you searched for = $tekst

searched in = $path/$files

Total number of file(s) matching search criteria = `wc -l ~/searchstring.txt  | awk '{print $1}'`

Total size of the matching file(s) = $totalsize
\E[0m

"
confirmyes "
Do you want to review the matches found? [Y/n]"

if ! [ "$?" -eq 0 ]; then
  exit 0
elif dpkg-query -l pluma | grep "ii" > /dev/null 2>&1; then
  pluma ~/searchstring.txt
elif dpkg-query -l gedit | grep "ii" > /dev/null 2>&1; then
  gedit ~/searchstring.txt
else
  cat ~/searchstring.txt | less
fi
